// <auto-generated />
using System;
using HCL_Hackathon_WebAPIators.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCL_Hackathon_WebAPIators.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525085814_AddIndianInventory")]
    partial class AddIndianInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "La Pino's India"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Domino's Corner"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Pizza Hut Premium"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mojo Pizza Co."
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ovenstory Semifredo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Coca-Cola India"
                        },
                        new
                        {
                            Id = 7,
                            Name = "PepsiCo Beverages"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Hector Beverages (Paper Boat)"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Amul Dairy Products"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Bisleri International"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Garlic Bread Masters"
                        },
                        new
                        {
                            Id = 12,
                            Name = "The Bakehouse Co."
                        },
                        new
                        {
                            Id = 13,
                            Name = "Britannia Foods"
                        },
                        new
                        {
                            Id = 14,
                            Name = "English Oven"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bonn Nutrients"
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drink"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bread"
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsSummaryBased")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HCLPIZZA10",
                            DiscountValue = 10.00m,
                            IsSummaryBased = true
                        },
                        new
                        {
                            Id = 2,
                            Code = "CRISP5",
                            DiscountValue = 5.00m,
                            IsSummaryBased = false
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliedCouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppliedCouponId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Packaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Packagings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Eco-Friendly Cardboard Pizza Box"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Recyclable Aluminium Can 330ml"
                        },
                        new
                        {
                            Id = 3,
                            Type = "PET Plastic Bottle 500ml"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Biodegradable Paper Food Wrap"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Glass Bottle Premium Premium"
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackagingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PackagingId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Name = "Classic Margherita Pizza",
                            PackagingId = 1,
                            Price = 249.00m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            CategoryId = 1,
                            Name = "Double Cheese Margherita",
                            PackagingId = 1,
                            Price = 389.00m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CategoryId = 1,
                            Name = "Fiery Paneer Tikka Pizza",
                            PackagingId = 1,
                            Price = 429.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 3,
                            CategoryId = 1,
                            Name = "Veggie Supreme Feast",
                            PackagingId = 1,
                            Price = 499.00m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 2,
                            CategoryId = 1,
                            Name = "Chicken Dominator Special",
                            PackagingId = 1,
                            Price = 599.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 4,
                            CategoryId = 1,
                            Name = "Spicy Triple Chicken Pizza",
                            PackagingId = 1,
                            Price = 649.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 1,
                            CategoryId = 1,
                            Name = "Capsicum & Sweet Corn Classic",
                            PackagingId = 1,
                            Price = 299.00m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 5,
                            CategoryId = 1,
                            Name = "4-Cheese Pizza Blast",
                            PackagingId = 1,
                            Price = 519.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            CategoryId = 1,
                            Name = "Indi Tandoori Paneer Premium",
                            PackagingId = 1,
                            Price = 459.00m,
                            StockQuantity = 38
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 3,
                            CategoryId = 1,
                            Name = "Pepper Chicken Exotic Pizza",
                            PackagingId = 1,
                            Price = 579.00m,
                            StockQuantity = 32
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 4,
                            CategoryId = 1,
                            Name = "Farmvilla Garden Special",
                            PackagingId = 1,
                            Price = 419.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 5,
                            CategoryId = 1,
                            Name = "Tikka Masala Chicken Feast",
                            PackagingId = 1,
                            Price = 589.00m,
                            StockQuantity = 28
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 1,
                            CategoryId = 1,
                            Name = "Cheesy Mushroom Delight",
                            PackagingId = 1,
                            Price = 379.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            CategoryId = 1,
                            Name = "Fiery Jalapeno & Paprika Spicy",
                            PackagingId = 1,
                            Price = 399.00m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 2,
                            CategoryId = 1,
                            Name = "Chicken Keema Makhani",
                            PackagingId = 1,
                            Price = 619.00m,
                            StockQuantity = 22
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 1,
                            CategoryId = 1,
                            Name = "Classic Onion & Tomato Single",
                            PackagingId = 1,
                            Price = 199.00m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 4,
                            CategoryId = 1,
                            Name = "Peri Peri Veggie Blast",
                            PackagingId = 1,
                            Price = 439.00m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 5,
                            CategoryId = 1,
                            Name = "Malai Tikka Chicken Supreme",
                            PackagingId = 1,
                            Price = 629.00m,
                            StockQuantity = 24
                        },
                        new
                        {
                            Id = 19,
                            BrandId = 3,
                            CategoryId = 1,
                            Name = "Exotic Italian Garden Pizza",
                            PackagingId = 1,
                            Price = 489.00m,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 20,
                            BrandId = 2,
                            CategoryId = 1,
                            Name = "Ultimate Non-Veg Overload",
                            PackagingId = 1,
                            Price = 699.00m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 21,
                            BrandId = 6,
                            CategoryId = 2,
                            Name = "Coca-Cola Aerated Can",
                            PackagingId = 2,
                            Price = 40.00m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 22,
                            BrandId = 6,
                            CategoryId = 2,
                            Name = "Diet Coke Zero Sugar",
                            PackagingId = 2,
                            Price = 45.00m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 23,
                            BrandId = 6,
                            CategoryId = 2,
                            Name = "Thums Up Strong Spice Can",
                            PackagingId = 2,
                            Price = 40.00m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 24,
                            BrandId = 7,
                            CategoryId = 2,
                            Name = "Pepsi Fizz Cola Can",
                            PackagingId = 2,
                            Price = 38.00m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 25,
                            BrandId = 7,
                            CategoryId = 2,
                            Name = "Mirinda Orange Fruity Can",
                            PackagingId = 2,
                            Price = 38.00m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 26,
                            BrandId = 6,
                            CategoryId = 2,
                            Name = "Sprite Lime Refresher Can",
                            PackagingId = 2,
                            Price = 40.00m,
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 27,
                            BrandId = 8,
                            CategoryId = 2,
                            Name = "Paper Boat Mango Juice Premium",
                            PackagingId = 4,
                            Price = 50.00m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 28,
                            BrandId = 8,
                            CategoryId = 2,
                            Name = "Paper Boat Aam Panna Tangy",
                            PackagingId = 4,
                            Price = 50.00m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 29,
                            BrandId = 9,
                            CategoryId = 2,
                            Name = "Amul Kool Premium Kesar Almond",
                            PackagingId = 5,
                            Price = 40.00m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 30,
                            BrandId = 9,
                            CategoryId = 2,
                            Name = "Amul Rose Milk Shake Bottle",
                            PackagingId = 5,
                            Price = 35.00m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 31,
                            BrandId = 9,
                            CategoryId = 2,
                            Name = "Amul Buttermilk Masti Spiced",
                            PackagingId = 4,
                            Price = 20.00m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 32,
                            BrandId = 10,
                            CategoryId = 2,
                            Name = "Bisleri Mineral Drinking Water",
                            PackagingId = 3,
                            Price = 20.00m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 33,
                            BrandId = 10,
                            CategoryId = 2,
                            Name = "Vedica Himalayan Spring Glass",
                            PackagingId = 5,
                            Price = 60.00m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 34,
                            BrandId = 7,
                            CategoryId = 2,
                            Name = "7Up Lemon Clear Refresh Bottle",
                            PackagingId = 3,
                            Price = 35.00m,
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 35,
                            BrandId = 6,
                            CategoryId = 2,
                            Name = "Minute Maid Pulpy Orange Pack",
                            PackagingId = 3,
                            Price = 45.00m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 36,
                            BrandId = 11,
                            CategoryId = 3,
                            Name = "Classic Cheesy Garlic Breadsticks",
                            PackagingId = 4,
                            Price = 149.00m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 37,
                            BrandId = 11,
                            CategoryId = 3,
                            Name = "Stuffed Paneer Garlic Breadsticks",
                            PackagingId = 4,
                            Price = 179.00m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 38,
                            BrandId = 12,
                            CategoryId = 3,
                            Name = "Gourmet Cheese & Jalapeno Bread",
                            PackagingId = 4,
                            Price = 189.00m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 39,
                            BrandId = 13,
                            CategoryId = 3,
                            Name = "Britannia Premium Fruit Bread Loaf",
                            PackagingId = 4,
                            Price = 50.00m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 40,
                            BrandId = 13,
                            CategoryId = 3,
                            Name = "Britannia 100-Percent Whole Wheat",
                            PackagingId = 4,
                            Price = 45.00m,
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 41,
                            BrandId = 14,
                            CategoryId = 3,
                            Name = "English Oven Gourmet Sandwich Loaf",
                            PackagingId = 4,
                            Price = 55.00m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 42,
                            BrandId = 14,
                            CategoryId = 3,
                            Name = "English Oven Atta Whole Wheat",
                            PackagingId = 4,
                            Price = 50.00m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 43,
                            BrandId = 15,
                            CategoryId = 3,
                            Name = "Bonn Atta High Fiber Pack",
                            PackagingId = 4,
                            Price = 42.00m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 44,
                            BrandId = 11,
                            CategoryId = 3,
                            Name = "Spicy Chicken Kheema Stuffed Bread",
                            PackagingId = 4,
                            Price = 219.00m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 45,
                            BrandId = 11,
                            CategoryId = 3,
                            Name = "Corn & Kernel Cheese Stuffed Bread",
                            PackagingId = 4,
                            Price = 169.00m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 46,
                            BrandId = 12,
                            CategoryId = 3,
                            Name = "French Sourdough Artisanal Baguette",
                            PackagingId = 4,
                            Price = 129.00m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 47,
                            BrandId = 12,
                            CategoryId = 3,
                            Name = "Italian Herbs Focaccia Loaf",
                            PackagingId = 4,
                            Price = 159.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 48,
                            BrandId = 14,
                            CategoryId = 3,
                            Name = "Multi-Grain Fitness Rich Loaf",
                            PackagingId = 4,
                            Price = 65.00m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 49,
                            BrandId = 14,
                            CategoryId = 3,
                            Name = "Sweet Honey & Oats Breakfast Loaf",
                            PackagingId = 4,
                            Price = 70.00m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 50,
                            BrandId = 15,
                            CategoryId = 3,
                            Name = "Bonn Premium White Milky Loaf",
                            PackagingId = 4,
                            Price = 38.00m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 51,
                            BrandId = 12,
                            CategoryId = 3,
                            Name = "Garlic Pull-Apart Cheese Bomb Loaf",
                            PackagingId = 4,
                            Price = 199.00m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 52,
                            BrandId = 13,
                            CategoryId = 3,
                            Name = "Britannia Brown Bread Wheat Loaf",
                            PackagingId = 4,
                            Price = 48.00m,
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 53,
                            BrandId = 11,
                            CategoryId = 3,
                            Name = "Cheese Stuffed Garlic Calzone Bread",
                            PackagingId = 4,
                            Price = 159.00m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 54,
                            BrandId = 12,
                            CategoryId = 3,
                            Name = "Exotic Olive & Oregano Loaf",
                            PackagingId = 4,
                            Price = 149.00m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 55,
                            BrandId = 14,
                            CategoryId = 3,
                            Name = "English Oven Premium Pav Bun Pack",
                            PackagingId = 4,
                            Price = 40.00m,
                            StockQuantity = 180
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@pizza.com",
                            LoyaltyPoints = 100,
                            PasswordHash = "$2a$11$OfA1PLLf6/9PdAAtGCImOOYS1ZZ3E6A6i2UqAws2.Ugsk4D1ERclK",
                            Role = "Manager",
                            Username = "Sanjana Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john@customer.com",
                            LoyaltyPoints = 25,
                            PasswordHash = "$2a$11$diqJ3YjKcFsCV5/cRx1chehp74tT5.5g4H916uczjkF3RaOWy0kQW",
                            Role = "Customer",
                            Username = "John Guest"
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Order", b =>
                {
                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Coupon", "AppliedCoupon")
                        .WithMany("Orders")
                        .HasForeignKey("AppliedCouponId");

                    b.HasOne("HCL_Hackathon_WebAPIators.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppliedCoupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.OrderItem", b =>
                {
                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Product", b =>
                {
                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Packaging", "Packaging")
                        .WithMany("Products")
                        .HasForeignKey("PackagingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Packaging");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Coupon", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Packaging", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
