// <auto-generated />
using System;
using HCL_Hackathon_WebAPIators.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HCL_Hackathon_WebAPIators.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260525082801_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pizza Express Brand"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beverage Craft Brand"
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Drink"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bread"
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("IsSummaryBased")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HCLPIZZA10",
                            DiscountValue = 10.00m,
                            IsSummaryBased = true
                        },
                        new
                        {
                            Id = 2,
                            Code = "CRISP5",
                            DiscountValue = 5.00m,
                            IsSummaryBased = false
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliedCouponId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppliedCouponId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Packaging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Packagings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Cardboard Box"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Aluminium Can"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Paper Wrapper"
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PackagingId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PackagingId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1,
                            Name = "Margherita Feast Pizza",
                            PackagingId = 1,
                            Price = 12.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 1,
                            Name = "Fiery Chicken Tikka Pizza",
                            PackagingId = 1,
                            Price = 15.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CategoryId = 3,
                            Name = "Cheesy Garlic Sticks",
                            PackagingId = 3,
                            Price = 5.49m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            CategoryId = 2,
                            Name = "Ice Cold Cola Premium",
                            PackagingId = 2,
                            Price = 2.49m,
                            StockQuantity = 100
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LoyaltyPoints")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@pizza.com",
                            LoyaltyPoints = 100,
                            PasswordHash = "$2a$11$3hMy4flqWu1I9R/5AgRS/ux4P4kG9zNwlhWhaAL5JbecvDAEvehvK",
                            Role = "Manager",
                            Username = "Sanjana Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john@customer.com",
                            LoyaltyPoints = 25,
                            PasswordHash = "$2a$11$JYZdgKe/Oiv9NLBd6vkMAuyF0CuBtzXsfycq3NmMe3IOTWVs8Betu",
                            Role = "Customer",
                            Username = "John Guest"
                        });
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Order", b =>
                {
                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Coupon", "AppliedCoupon")
                        .WithMany("Orders")
                        .HasForeignKey("AppliedCouponId");

                    b.HasOne("HCL_Hackathon_WebAPIators.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppliedCoupon");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.OrderItem", b =>
                {
                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Product", b =>
                {
                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HCL_Hackathon_WebAPIators.Models.Packaging", "Packaging")
                        .WithMany("Products")
                        .HasForeignKey("PackagingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");

                    b.Navigation("Packaging");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Coupon", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Packaging", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("HCL_Hackathon_WebAPIators.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
